"""create commission_config table

Revision ID: 4d3e8f603965
Revises: 71d0f055ead8
Create Date: 2025-09-05 22:18:58.449365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3e8f603965'
down_revision: Union[str, None] = '71d0f055ead8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_earnings', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('referral_earnings', sa.Column('commission_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_earnings', 'commission_amount')
    op.drop_column('referral_earnings', 'percentage')
    # ### end Alembic commands ###
