"""add max_roi_multiplier to roi_config

Revision ID: 0a903933cdb4
Revises: 6525a2695137
Create Date: 2025-09-15 19:07:44.584767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a903933cdb4'
down_revision: Union[str, None] = '6525a2695137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lock_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associate_config_id'), 'associate_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_associate_config_id'), table_name='associate_config')
    op.drop_table('associate_config')
    # ### end Alembic commands ###
