"""add max_roi_multiplier to roi_config

Revision ID: 242a26c6c63d
Revises: a928620826f2
Create Date: 2025-09-12 00:20:28.332625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242a26c6c63d'
down_revision: Union[str, None] = 'a928620826f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('roi_received', sa.Float(), nullable=True))
    op.add_column('investments', sa.Column('flushed', sa.Boolean(), nullable=True))
    op.add_column('roi_config', sa.Column('max_roi_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roi_config', 'max_roi_multiplier')
    op.drop_column('investments', 'flushed')
    op.drop_column('investments', 'roi_received')
    # ### end Alembic commands ###
