"""init full schema

Revision ID: 4e34a06ca19a
Revises: e8b46ef59ddf
Create Date: 2025-09-06 18:41:24.854634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e34a06ca19a'
down_revision: Union[str, None] = 'e8b46ef59ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_config_id'), 'commission_config', ['id'], unique=False)
    op.create_table('referral_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_email', sa.String(), nullable=True),
    sa.Column('referred_email', sa.String(), nullable=True),
    sa.Column('investment_amount', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_earnings_id'), 'referral_earnings', ['id'], unique=False)
    op.create_index(op.f('ix_referral_earnings_referred_email'), 'referral_earnings', ['referred_email'], unique=False)
    op.create_index(op.f('ix_referral_earnings_referrer_email'), 'referral_earnings', ['referrer_email'], unique=False)
    op.create_table('roi_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roi_config_id'), 'roi_config', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_lower', sa.String(), nullable=True),
    sa.Column('is_associate', sa.Boolean(), nullable=True),
    sa.Column('pending_associate', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('referred_by', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['users.referral_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('wallet')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_lower'), 'users', ['email_lower'], unique=True)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', name='uq_tx_hash')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.create_index(op.f('ix_investments_tx_hash'), 'investments', ['tx_hash'], unique=True)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_investments_tx_hash'), table_name='investments')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_users_email_lower'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roi_config_id'), table_name='roi_config')
    op.drop_table('roi_config')
    op.drop_index(op.f('ix_referral_earnings_referrer_email'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_referred_email'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_id'), table_name='referral_earnings')
    op.drop_table('referral_earnings')
    op.drop_index(op.f('ix_commission_config_id'), table_name='commission_config')
    op.drop_table('commission_config')
    # ### end Alembic commands ###
