"""init full schema

Revision ID: 50713b398775
Revises: 4e34a06ca19a
Create Date: 2025-09-07 22:08:37.436993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50713b398775'
down_revision: Union[str, None] = '4e34a06ca19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('last_roi_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'last_roi_date')
    # ### end Alembic commands ###
