"""add direct_referral_bonus table

Revision ID: d613af30351c
Revises: 0a903933cdb4
Create Date: 2025-09-22 16:50:56.220565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd613af30351c'
down_revision: Union[str, None] = '0a903933cdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_referral_bonus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_email', sa.String(), nullable=False),
    sa.Column('referee_email', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('bonus_amount', sa.Float(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lock_days', sa.Integer(), nullable=True),
    sa.Column('matured_at', sa.DateTime(), nullable=True),
    sa.Column('flushed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['referee_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['referrer_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_referral_bonus_id'), 'direct_referral_bonus', ['id'], unique=False)
    op.create_index(op.f('ix_direct_referral_bonus_tx_hash'), 'direct_referral_bonus', ['tx_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direct_referral_bonus_tx_hash'), table_name='direct_referral_bonus')
    op.drop_index(op.f('ix_direct_referral_bonus_id'), table_name='direct_referral_bonus')
    op.drop_table('direct_referral_bonus')
    # ### end Alembic commands ###
